---
- name: create app directory
  file: 
    path: /home/ubuntu/backend
    state: directory

-name: unarchive files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: start app
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm start /home/ubuntu/backend/dist/main.js --name

