---
- name: unarchive files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: start app
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm -- start  

