---
- name: create app directory
  file: 
    path: /home/ubuntu/backend/
    state: directory

- name: unarchive files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/

- name: install dependencies
  shell: | 
    cd /home/ubuntu/backend/
    npm i

- name: start app
  shell: |
    cd /home/ubuntu/backend/
    sudo pm2 stop default
    sudo pm2 start dist/main.js

  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.c5qgzjqwg3ed.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: post1234
    TYPEORM_DATABASE: postgres


