---
- name: create app directory
  file: 
    path: /home/ubuntu/backend/
    state: directory

- name: unarchive files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/

- name: install dependencies
  shell: | 
    cd /home/ubuntu/backend/
    npm install

- name: start app
  shell: |
    cd /home/ubuntu/backend/dist
    sudo pm2 stop default
    sudo pm2 start main.js

- name: "enable service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save    


