---
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  become_method: sudo
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
   autoremove: yes

- name: "install node dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes  

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: extract artifact
  become: yes
  unarchive:
    remote_src: yes
    src: ~/backend/artifact.tar.gz

- name: install app
  npm:
    install

- name: start app
  pm2:
    stop default
    start npm -- start

