---
- name: unarchive files
  unarchive:
    src: /project/artifact.tar.gz
    dest: /home/ubuntu/

- name: start app
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start  

